name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Add pnpm to PATH
        run: echo "::add-path::$(npm bin -g)"

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Print Node.js version
        run: node --version

      - name: Print npm version
        run: npm --version
        
      - name: Build Astro project
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Adjust this path if your build output is in a different directory
          cname: your-custom-domain.com # Optional: If you have a custom domain, add it here
