name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Uncomment this step if you encounter issues with pnpm compatibility
      # - name: Install compatible pnpm version
      #   run: npm install -g pnpm@6.16.0
      #   Replace '6.16.0' with the compatible version of pnpm for Node.js 14.21.3

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Add pnpm to PATH
        run: echo "::add-path::$(npm bin -g)"
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Astro project
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Adjust this path if your build output is in a different directory
          cname: your-custom-domain.com # Optional: If you have a custom domain, add it here
