name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # If you choose to upgrade Node.js, skip this step
      - name: Install compatible pnpm version
        run: npm install -g pnpm@<compatible_version>
        # Replace <compatible_version> with the version of pnpm that supports Node.js 14.21.3

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Add pnpm to PATH
        run: echo "::add-path::$(npm bin -g)"
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Astro project
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Adjust this path if your build output is in a different directory
          cname: your-custom-domain.com # Optional: If you have a custom domain, add it here
